version: '3.4'

services:
  web:
    image: app_garage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./environments/.env_local_dev
    depends_on:
      - db
      # - cache
    links:
      - db
      # - cache
    command: python manage.py runserver 0.0.0.0:8000
      
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_user
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  # cache:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
