version: '3.4'

services:
  web:
    image: my_garage:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    platform: linux/amd64
    env_file:
      - ./environments/.env_local_dev
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    volumes:
      - /tmp/app_resources/static:/app/staticfiles
    command: gunicorn --bind=0.0.0.0:8000 my_garage.wsgi:application
      
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_user
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/app_resources/static:/home/app/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
  