version: '3.4'

services:
  web:
    image: kostakazakoff/mygarage:1.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    platform: linux/amd64
    env_file:
      - ./environments/.env_prod
    depends_on:
      - db
    links:
      - db
    volumes:
      - /tmp/app_resources/static:/app/static
      - /tmp/app_resources/media:/app/mediafiles/
    command: gunicorn --bind=0.0.0.0:8000 -w 4 my_garage.wsgi:application; celery -A my_garage.celery worker -l info 
      
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_user
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/app_resources/static:/home/app/web/staticfiles/
      - /tmp/app_resources/media:/home/app/web/mediafiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
  