version: '3.4'

services:
  web:
    image: app_garage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    platform: linux/amd64
    env_file:
      - ./environments/.env_local_dev
    depends_on:
      - db
    links:
      - db
    volumes:
      - /tmp/for_deploy/static:/app/static
    command: gunicorn --bind=0.0.0.0:8000 for_deploy.wsgi:application
      
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_user
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  # cache:
  #   container_name: mygarage-cache-redis
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  