version: '3.4'

services:
  web:
    image: mygarage
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./environments/.env_local_dev
  postgres:
    container_name: garage
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: MyProjects
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .mygarage:/var/lib/postgresql/data
  # cache:
  #   container_name: mygarage-cache-redis
  #   image: redis
  #   restart: always
  #   ports:
  #     -"6379:6379"