version: '3.4'

services:
  web:
    image: mygarage
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./environments/.env_local_dev
    depends_on:
      - db
  db:
    container_name: garage
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: garage
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./mygarage:/var/lib/postgresql/data
  # cache:
  #   container_name: mygarage-cache-redis
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"




# version: '3'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./environments/.env_local_dev
#     volumes:
#       - .:/app
#     depends_on:
#       - postgres
#       - redis

#   postgres:
#     image: postgres:latest
#     ports:
#         - "5432:5432"
#     environment:
#       DB_NAME: garage
#       POSTGRES_PASSWORD: root
#       POSTGRES_USER: root
#       POSTGRES_DB: MyProjects
#       PGDATA: /var/lib/postgresql/data/pgdata
#     volumes:
#       - .mygarage:/var/lib/postgresql/data

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"

# volumes:
#   .mygarage:/var/lib/postgresql/data/pgdata
