version: '3.4'

services:
  web:
    image: app_garage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./environments/.env.dev
    depends_on:
      - db
      - celery_worker
    links:
      - db
      - celery_worker
    command: python manage.py runserver 0.0.0.0:8000
      
  db:
    image: postgres
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_user
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  celery_worker:
      image: app_garage
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./environments/.env.dev
      depends_on:
        - db
        # - broker
      links:
        - db
        # - broker
      command: celery -A my_garage.celery worker -l info --concurrency=4

  # broker:
  #   image: redis:7.2-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
