# Generated by Django 4.2.1 on 2023-05-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('odometer', models.IntegerField(max_length=6)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
