# Generated by Django 4.2.1 on 2023-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('plate', models.CharField(max_length=10)),
                ('odometer', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ('-date_of_purchase',),
            },
        ),
    ]
