# Generated by Django 4.1.7 on 2023-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(blank=True, choices=[('cake', 'Торта'), ('peace_of_cake', 'Паста'), ('other', 'Други'), ('complex_product', 'Заготовка')], max_length=100, verbose_name='Вид')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('pieces', models.IntegerField(blank=True, default=16, null=True, verbose_name='Брой')),
                ('weigth_g', models.IntegerField(blank=True, default=0, null=True, verbose_name='Тегло')),
                ('weigth_per_piece_g', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Тегло/бр.')),
                ('electricity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Ток')),
                ('water', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Вода')),
                ('worker_expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Работа')),
                ('package', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Опаковки')),
                ('fuel', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Гориво')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Себестойност')),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Други разходи 10%')),
                ('manufacturing_costs', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Производствени загуби 8%')),
                ('final_costs_price', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Общо себестойност')),
                ('workshop_profit', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Печалба цех 10%')),
                ('workshop_price', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Цена цех')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='ДДС')),
                ('price_incl_vat', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Стойност с ДДС')),
                ('price_incl_vat_per_piece', models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=10, verbose_name='Стойност с ДДС')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Забележка')),
                ('reciep', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Рецепта')),
                ('cake_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Снимка')),
                ('products', models.ManyToManyField(related_name='articles', to='products.product', verbose_name='Продукти')),
            ],
        ),
    ]
