# Generated by Django 4.1.7 on 2023-02-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='Продукти'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='ComplexProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, choices=[('л.', 'л.'), ('кг.', 'кг.'), ('кв/ч.', 'кв/ч.'), ('бр.', 'бр.'), ('мин.', 'мин.')], max_length=10, null=True, verbose_name='Мярка')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Количество')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Забележка')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='Продукти')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='complex_products',
            field=models.ManyToManyField(to='products.complexproduct', verbose_name='Продукти'),
        ),
    ]
