# Generated by Django 4.1.7 on 2023-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_article_products_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, choices=[('cake', 'Торта'), ('peace_of_cake', 'Паста'), ('other', 'Други')], max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='complexproduct',
            name='unit',
            field=models.CharField(blank=True, choices=[('кг.', 'кг.'), ('л.', 'л.'), ('бр.', 'бр.'), ('мин.', 'мин.'), ('кв/ч.', 'кв/ч.')], max_length=10, null=True, verbose_name='Мярка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('кг.', 'кг.'), ('л.', 'л.'), ('бр.', 'бр.'), ('мин.', 'мин.'), ('кв/ч.', 'кв/ч.')], default='бр.', max_length=10, null=True, verbose_name='Мярка'),
        ),
    ]
