# Generated by Django 4.1.7 on 2023-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_complexproduct_price_alter_article_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='complexproduct',
            name='unit',
            field=models.CharField(blank=True, choices=[('кг.', 'кг.'), ('л.', 'л.'), ('бр.', 'бр.'), ('мин.', 'мин.'), ('кв/ч.', 'кв/ч.')], default='бр.', max_length=10, null=True, verbose_name='Мярка'),
        ),
    ]
