# Generated by Django 4.1.7 on 2023-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_complexproduct_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=None, max_digits=100, verbose_name='Цена'),
        ),
    ]
