# Generated by Django 4.1.7 on 2023-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_complexproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexproduct',
            name='unit',
            field=models.CharField(blank=True, choices=[('г.', 'г.'), ('л.', 'л.'), ('бр.', 'бр.'), ('мин.', 'мин.'), ('кв/ч.', 'кв/ч.')], default='бр.', max_length=10, null=True, verbose_name='Мярка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('г.', 'г.'), ('л.', 'л.'), ('бр.', 'бр.'), ('мин.', 'мин.'), ('кв/ч.', 'кв/ч.')], default='бр.', max_length=10, null=True, verbose_name='Мярка'),
        ),
    ]
