# Generated by Django 4.1.7 on 2023-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_complexproduct_product_03_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexproduct',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Количество'),
        ),
    ]
