# Generated by Django 4.1.7 on 2023-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_complexproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexproduct',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, verbose_name='Количество на заготовката'),
        ),
    ]
