# Generated by Django 4.1.7 on 2023-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_complexproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cake_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='Снимка'),
        ),
    ]
